on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6,26,46 * * * *' # every twenty minutes

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install xml-js
      run: npm install xml-js

    - name: Fetch latest data from the API endpoint
      run: |
        currentTime=$(date +%s%3N)
        echo "Current time: ${currentTime}"
        curl -sk "https://tsunami.incois.gov.in/itews/homexmls/seismic.xml?currentTime=currentTime=${currentTime}" -o events.xml
        node convert-xml-to-json.js
        cat sensorList.json # Output json
    - name: Commit and push if the data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
